# Site settings
title: Hafiyyan Sayyid Fadhlillah
email: hafiyyan.fadhlillah@jku.at
description: Academic webpage of Hafiyyan Sayyid Fadhlillah
baseurl: ""
url: "https://hafiyyansayy.id"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Hafiyyan Sayyid Fadhlillah<br/>
  Doctorate Student<br/>
  Johannes Kepler University Linz

location: >
  Johannes Kepler University Linz<br/>
  Altenberger Strasse 69<br/>
  Linz, AT 4040

contact: >
  <a href="mailto:hafiyyan.fadhlillah@jku.at" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Sayyid via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  - name: project
  - name: supervision
  - name: teaching
  - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Fadhlillah
  first_name: [Hafiyyan Sayyid]

  style: citesty
  locale: en

  source: /assets/bibliography/
  bibliography: "*.bib"
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
